version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopnow-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb+srv://syed9848314_db_user:yvABspjaU9G3ocj5@cluster0.z6sy8q6.mongodb.net/shopnow
      JWT_SECRET: shopnow-secret


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shopnow-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: shopnow-admin
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend

