apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-admin
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopnow-admin
  template:
    metadata:
      labels:
        app: shopnow-admin
    spec:
      containers:
        - name: admin
          image: imran7012/shopnow-admin:latest
          ports:
            - containerPort: 80
