apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-frontend
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopnow-frontend
  template:
    metadata:
      labels:
        app: shopnow-frontend
    spec:
      containers:
        - name: frontend
          image: imran7012/shopnow-frontend:latest
          ports:
            - containerPort: 80
