apiVersion: v1
kind: Secret
metadata:
  name: shopnow-secret
  namespace: shopnow
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://syed9848314_db_user:yvABspjaU9G3ocj5@cluster0.z6sy8q6.mongodb.net/shopnow
  JWT_SECRET: shopnow-secret
