apiVersion: v1
kind: Service
metadata:
  name: shopnow-admin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: shopnow-admin
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
  type: ClusterIP
