apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnow-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shopnow-frontend
  template:
    metadata:
      labels:
        app: shopnow-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
