apiVersion: v1
kind: Secret
metadata:
  name: shopnow-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGODB_URI: "{{ .Values.env.backend.MONGODB_URI }}"
  JWT_SECRET: "{{ .Values.env.backend.JWT_SECRET }}"
